setwd("C:/Users/user/Dropbox/R_project/aspep/data/raw_datasets")
devtools::install_github("jacobkap/asciiSetupReader")
library(asciiSetupReader)


id_value_labels <- data.frame(value = c("state code",
                                        "00", "01", "02", "03", "04",
                                        "05", "06", "07", "08", "09",
                                        10:51,
                                        "type of government code",
                                        "0", "1", "2", "3", "4",
                                        "5", "6",
                                        "school level code",
                                        "01", "02", "03", "04", "05", "06", "07",
                                        "weekly hours code",
                                        "1", "2", "3", "4", "5",
                                        "full-time pay code",
                                        "1", "2", "3", "4",
                                        "part-time pay code",
                                        "1", "2", "3", "4",
                                        "year of data",
                                        "99", "II", "NN"), 
                              label =   c("",
                                          tolower(c("united states", 
                                                    sort(c(state.name,
                                                           "district of columbia")))),
                                          "",
                                          "state",
                                          "county",
                                          "municipal",
                                          "township",
                                          "special district",
                                          "school district",
                                          "u.s. government",
                                          "",
                                          "elementary only",
                                          "secondary only",
                                          "elementary and secondary",
                                          "higher education only",
                                          "special independent vocational or special education",
                                          "non-operating",
                                          "education service agency (ESA)",
                                          "",
                                          "39 or more",
                                          "37.5-38.9",
                                          "34-37.4",
                                          "32-33.9",
                                          "30-31.9",
                                          "",
                                          "monthly",
                                          "twice a month",
                                          "each 2 weekly",
                                          "weekly",
                                          "",
                                          "monthly",
                                          "twice a month",
                                          "each 2 weeks",
                                          "weekly",
                                          "",
                                          "response for 1999",
                                          "data imputed",
                                          "no information for this unit"),
                              stringsAsFactors = FALSE)

data_value_labels <- data.frame(value = c("data function item code",
                                          "000", "001", "002", "005",
                                          "006", "012", "112", "014",
                                          "016", "018", "021", "022",
                                          "023", "024", "124", "025", 
                                          "029", "032", "040", "044",
                                          "050", "052", "059", "061",
                                          "062", "162", "079", "080",
                                          "081", "087", "089", "090",
                                          "091", "092", "093", "094"),
                                label = c("",
                                          "total",
                                          "airports",
                                          "space research & technology (federal)",
                                          "correction",
                                          "national defense and international relations (federal)",
                                          "elementary and secondary - instruction",
                                          "elementary and secondary - other total",
                                          "postal service (federal)",
                                          "higher education - other",
                                          "higher education - instructional",
                                          "other education (state)",
                                          "social insurance administration (state)",
                                          "financial administration",
                                          "firefighters",
                                          "fire - other",
                                          "judicial & legal",
                                          "other government administration",
                                          "health",
                                          "hospitals",
                                          "streets & highways",
                                          "housing & community development (local)",
                                          "local libraries",
                                          "natural resources",
                                          "parks & recreation",
                                          "police protection - officers",
                                          "police - other",
                                          "welfare",
                                          "sewerage",
                                          "solid waste management",
                                          "water transport & terminals",
                                          "other & unallocable",
                                          "liquor stores (state)",
                                          "water supply",
                                          "electric power",
                                          "gas supply",
                                          "transit"
                                ),
                                stringsAsFactors = FALSE)


flag_values <- c('"C"', '"R"', '"T"', '"U"', '"V"', '"A"', '"B"', '"D"',
                 '"G"', '"I"', '"J"', '"P"', '"Q"', '"S"', '"Z"', '"X"')
flag_labels <- c("Without contacting the respondent, the analyst corrects data provided in an inappropriate item code or individual unit, corrects data so detail adds to total, corrects other reported minor reporting errors that prevents the use of the original data provided by the respondent.",
                 "1) Data item is reported directly by the respondent. 2) Respondent does not complete the survey form, but provides additional information which is compiled and used to complete the form, i.e., annual report, Website, etc.",
                 "Respondent reports totals and these data are prorated based on the prior year distribution.",
                 "Analyst obtains correct data from the respondent via telephone, e-mail, or fax.",
                 "1) Analyst verifies the data with the respondent via telephone, e-mail, or fax. 2) Analyst corrects improperly keyed data and replaces with the reported values from the questionnaire.",
                 "Missing or inappropriate data fixed by computer calculations are based on prior year factors or prior year state averages.",
                 "Analyst obtains information from a report or other administrative source without prior respondent contact and there exists documentation verifying that these data sources are comparable to reported data.",
                 "Analyst obtains information from a Website without prior respondent contact and there exists documentation verifying that these data sources are comparable to reported data.",
                 "The prior year data were adjusted by a growth rate that was determined by the growth of responding units that were similar to the nonrespondent in size, geography and type of government.",
                 "For Regional Occupational Programs (ROP) units, zeroes were imputed since the prior year data consisted of all zeroes.",
                 "The unit contained partially reported data sufficient to determine unit totals at the total employee/total pay level. Data were imputed using pro-rated values based on prior year or cell median ratios. Flag J differs from Flag T in that Flag T implies that the unit total for that variable was reported, e.g., if full-time pay is reported, then full-time pay for each item code of that unit will receive a flag of T. While Flag J implies that the unit total for that variable was not reported, e.g., if total employees are reported, but neither full-time nor part-time employees are reported, then full-time employees will be pro--rated and full-time employees for each item code of that unit will receive a flag of J.",
                 "Data were from a donor that was randomly selected from units similar to the nonrespondent. A per capita adjustment based on population enrollment was made.",
                 "A growth rate was applied to the prior year that carried a flag of P.",
                 "This flag is used for imputed values of part-time hours. Part-time hours are imputed as the value of the item code's part-time employees multiplied by the unit's average part-time hours per employee for the given item code in the prior year. If the given item code in the prior year is not available, then the median average part-time hours per employee for the given item code is used instead. The median is calculated for the current year data in the unit's imputation cell.",
                 "Data are the summation of multiple individual state agencies (i.e., state level data) or the summation of multiple data function codes (i.e., total data function code of '000'').",
                 "The analyst creates a value missing entry, an erroneous reported entry, or an imputed value without contacting the respondent.")

flag_value_labels <- data.frame(value = c("full-time employees data flag",
                                          flag_values,
                                          "full-time payroll data flag",
                                          flag_values,
                                          "part-time employees data flag",
                                          flag_values,
                                          "part-time payroll data flag",
                                          flag_values,
                                          "part-time hours data flag",
                                          flag_values),
                                label = c("",
                                          flag_labels,
                                          "",
                                          flag_labels,
                                          "",
                                          flag_labels,
                                          "",
                                          flag_labels,
                                          "",
                                          flag_labels),
                                stringsAsFactors = FALSE)


data_value_labels           <- dplyr::bind_rows(data_value_labels, state_value_labels)
data_value_labels_post_2001 <- dplyr::bind_rows(data_value_labels,
                                                flag_value_labels)

make_sps_setup(file_name     = "individual_unit_id_1992_2006",
               col_positions = c("1-2", "3-3", "4-6", "7-9", "10-12",
                                 "13-14", "15-78", "79-79", "80-109",
                                 "110-111", "112-114", "115-119",
                                 "120-123", "124-125", "126-134",
                                 "135-136", "137-138", "139-145",
                                 "146-151", "152-156", "157-186",
                                 "189-189", "190-190", "191-191",
                                 "192-193", "194-195", "196-197",
                                 "198-199", "200-201", "202-204",
                                 "205-206"),
               col_labels    = c("state code",
                                 "type of government code",
                                 "county code",
                                 "unit identification number",
                                 "supplement code",
                                 "sub code",
                                 "name of government/political description",
                                 "census region code",
                                 "county name",
                                 "fips state",
                                 "fips county",
                                 "fips place",
                                 "fips msa",
                                 "fips cmsa",
                                 "pop/enrollment/function code",
                                 "year of pop/enrollment",
                                 "school level code",
                                 "filler",
                                 "sample weight",
                                 "filler",
                                 "multi-county code",
                                 "weekly hours code",
                                 "full-time pay code",
                                 "part-time pay code",
                                 "number of months teachers paid",
                                 "number of months school admin paid",
                                 "number of months school other paid",
                                 "year of data",
                                 "year of dependent school data",
                                 "filler",
                                 "survey form type"),
               value_labels = id_value_labels)

make_sps_setup(file_name     = "individual_unit_data_1992_2006",
               col_positions = c("1-2", "3-3", "4-6", "7-9", "10-12",
                                 "13-14", "15-17", "18-20", "21-30",
                                 "31-42", "43-52", "53-64", "65-74",
                                 "75-84"),
               col_labels    = c("state code",
                                 "type of government code",
                                 "county code",
                                 "unit identification number",
                                 "supplement code",
                                 "sub code",
                                 "filler",
                                 "data function item code",
                                 "full-time employees",
                                 "full-time payroll",
                                 "part-time employees",
                                 "part-time payroll",
                                 "part-time hours",
                                 "full-time equivalent employees"),
               value_labels = data_value_labels)

make_sps_setup(file_name     = "individual_unit_id_2007_2011",
               col_positions = c("1-2", "3-3", "4-6", "7-9", "10-12",
                                 "13-14", "15-78", "79-79", "80-109",
                                 "110-111", "112-114", "115-119",
                                 "120-123", "124-125", "126-134",
                                 "135-136", "137-138", "139-145",
                                 "146-151", "152-156", "157-186",
                                 "187-188", "189-189", "190-190",
                                 "191-191", "192-193", "194-195",
                                 "196-197", "198-199", "200-201",
                                 "202-204", "205-206"),
               col_labels    = c("state code",
                                 "type of government code",
                                 "county code",
                                 "unit identification number",
                                 "supplement code",
                                 "sub code",
                                 "name of government/political description",
                                 "census region code",
                                 "county name",
                                 "fips state",
                                 "fips county",
                                 "filler",
                                 "filler",
                                 "filler",
                                 "population/enrollment/function code",
                                 "year of population/enrollment",
                                 "school level code",
                                 "filler",
                                 "sample weight",
                                 "filler",
                                 "filler",
                                 "filler",
                                 "weekly hours code",
                                 "full-time pay code",
                                 "part-time pay code",
                                 "number of months teachers paid",
                                 "number of months school admin paid",
                                 "number of months school other paid",
                                 "year of data",
                                 "year of dependent school data",
                                 "filler",
                                 "survey form type"),
               value_labels = id_value_labels)



make_sps_setup(file_name     = "individual_unit_data_2007_2011",
               col_positions = c("1-2", "3-3", "4-6", "7-9", "10-12", 
                                 "13-14", "15-17", "18-20", "21-30",
                                 "31-31", "32-32", "33-44", "45-45",
                                 "46-46", "47-56", "57-57", "58-58",
                                 "59-70", "71-71", "72-72", "73-82",
                                 "83-83", "84-84", "85-94", "95-95",
                                 "96-96"),
               col_labels    = c("state code",
                                 "type of government code",
                                 "county code",
                                 "unit identification number",
                                 "supplement code",
                                 "sub code",
                                 "filler",
                                 "data function item code",
                                 "full-time employees",
                                 "filler",
                                 "full-time employees data flag",
                                 "full-time payroll",
                                 "filler",
                                 "full-time payroll data flag",
                                 "part-time employees",
                                 "filler",
                                 "part-time employees data flag",
                                 "part-time payroll",
                                 "filler",
                                 "part-time payroll data flag",
                                 "part time hours",
                                 "filler",
                                 "part-time hours data flag",
                                 "full-time equivalent employees",
                                 "filler",
                                 "g-30 designation"),
               value_labels = data_value_labels_post_2001)


make_sps_setup(file_name     = "individual_unit_id_2012_2016",
               col_positions = c("1-2", "3-3", "4-6", "7-9", "10-12",
                                 "13-14", "15-78", "79-79", "80-109",
                                 "110-111", "112-114", "126-134",
                                 "135-136", "137-138", "146-151",
                                 "189-189", "190-190", "191-191",
                                 "192-193", "194-195", "196-197",
                                 "198-199", "200-201", "205-206"),
               col_labels    = c("state code",
                                 "type of government code",
                                 "county code",
                                 "unit identification number",
                                 "supplement code",
                                 "sub code",
                                 "name of government/political description",
                                 "census region code",
                                 "county name",
                                 "fips state",
                                 "fips county",
                                 "population/enrollment/function code",
                                 "year of population/enrollment",
                                 "school level code",
                                 "sample weight",
                                 "weekly hours code",
                                 "full-time pay code",
                                 "part-time pay code",
                                 "number of months teachers paid",
                                 "number of months school admin paid",
                                 "number of months school other paid",
                                 "year of data",
                                 "year of dependent school data",
                                 "survey form type"),
               value_labels = id_value_labels)


make_sps_setup(file_name     = "individual_unit_data_2012_2016",
               col_positions = c("1-2", "3-3", "4-6", "7-9", "10-12", "13-14",
                                 "18-20", "21-30", "32-32", "33-44", "46-46",
                                 "47-56", "58-58", "59-70", "72-72", "73-82",
                                 "84-84", "85-94"),
               col_labels    = c("state code",
                                 "type of government code",
                                 "county code",
                                 "unit identification number",
                                 "supplement code",
                                 "sub code",
                                 "data function item code",
                                 "full-time employees",
                                 "full-time employees data flag",
                                 "full-time payroll",
                                 "full-time payroll data flag",
                                 "part-time employees",
                                 "part-time employees data flag",
                                 "part-time payroll",
                                 "part-time payroll data flag",
                                 "part-time hours",
                                 "part-time hours data flag",
                                 "full-time equivalent employees"),
               value_labels = data_value_labels_post_2001)




